# states.py

class State:
    INIT = "INIT"
    CONNECTING = "CONNECTING"
    ARMING = "ARMING"
    TAKEOFF = "TAKEOFF"
    TRANSIT_TO_SEARCH = "TRANSIT_TO_SEARCH"
    SEARCH = "SEARCH"
    CENTERING = "CENTERING"
    DESCENDING = "DESCENDING"
    VERIFY = "VERIFY"
    HOVER = "HOVER"         
    APPROACH = "APPROACH"   
    LANDING = "LANDING"
    MANUAL = "MANUAL"
    SAFETY_HALT = "SAFETY_HALT" 
    DONE = "DONE"