/**
 * Hardware Data — All drone components, connections, setup guides, and links
 *
 * Each component has: what it is, what it connects to, setup steps, guides/docs links.
 * This is the comprehensive hardware reference for the SAR drone.
 */

export interface HardwareComponent {
  id: string;
  name: string;
  category: "airframe" | "flight-controller" | "navigation" | "companion" | "vision" | "radio" | "payload" | "software";
  role: string;
  description: string;
  status: "verified" | "partial" | "todo";
  connectsTo: string[]; // IDs of components it connects to
  connectionDetails?: string; // how it physically connects
  setupSteps: string[];
  guides: { label: string; url: string; description: string }[];
  specs?: { label: string; value: string }[];
  testCommands?: { command: string; expect: string }[];
  notes?: string[];
}

export const HARDWARE_COMPONENTS: HardwareComponent[] = [
  {
    id: "frame",
    name: "Hexsoon EDU-450",
    category: "airframe",
    role: "Quadcopter Airframe",
    description: "Education-grade quadcopter frame provided by the university. ~450mm wheelbase, X configuration. Carries all components: flight controller, companion computer, camera, GPS, battery, payload mechanism.",
    status: "verified",
    connectsTo: ["cube", "pi", "camera", "gps", "motors", "payload"],
    connectionDetails: "All components mount to the frame. Motors on arms, Cube on vibration dampener, Pi mounted with standoffs, camera underneath, GPS on mast.",
    setupSteps: [
      "Assemble frame per Hexsoon EDU-450 manual",
      "Mount motors on each arm (check rotation direction: CW/CCW alternating)",
      "Mount Cube Orange+ on vibration dampener plate (centre of gravity)",
      "Mount Pi 5 with standoffs (avoid vibration transfer from motors)",
      "Mount camera underneath frame (clear view downward, no propellers in FOV)",
      "Mount GPS mast on top (highest point, away from electronics/interference)",
      "Route and secure all cables (zip ties, no loose wires near props)",
    ],
    guides: [
      { label: "Hexsoon EDU-450 Manual", url: "https://docs.hexsoon.com", description: "Assembly instructions, motor layout, dimensions" },
    ],
    specs: [
      { label: "Wheelbase", value: "450mm" },
      { label: "Frame type", value: "QUAD/X" },
      { label: "Max takeoff weight", value: "~2.5kg" },
    ],
    notes: [
      "Check propeller direction before every flight — wrong prop on wrong motor = immediate flip",
      "Vibration dampener is critical — hard-mounting Cube causes IMU errors and crashes",
    ],
  },
  {
    id: "cube",
    name: "Cube Orange Plus",
    category: "flight-controller",
    role: "Flight Controller (Autopilot)",
    description: "The brain of the drone. Runs ArduCopter firmware, handles all flight dynamics (stabilisation, altitude hold, GPS navigation), failsafes, and motor control. All autonomous flight modes (GUIDED, AUTO, LOITER, RTL, LAND) are processed here.",
    status: "verified",
    connectsTo: ["gps", "pi", "rc-rx", "motors", "payload", "buzzer"],
    connectionDetails: "GPS via CAN2 port. Pi via TELEM2 (TX/RX/GND). RC receiver via RCIN. Motors via MAIN OUT 1-4. Payload servo via AUX OUT. Buzzer via BUZZER port. Power via power module on POWER1.",
    setupSteps: [
      "Flash ArduCopter firmware (V4.6.3 or latest stable) via Mission Planner",
      "Set frame type: FRAME_CLASS=1 (Quad), FRAME_TYPE=1 (X)",
      "Calibrate accelerometer (Mission Planner: Setup > Mandatory > Accel Calibration)",
      "Calibrate compass (Mission Planner: Setup > Mandatory > Compass, rotate in all axes)",
      "Calibrate RC (Mission Planner: Setup > Mandatory > Radio Calibration)",
      "Set SERIAL2_PROTOCOL=2 (MAVLink2) for TELEM2 -> Pi connection",
      "Set SERIAL2_BAUD=921 (921600 baud) to match mavproxy",
      "Set BRD_SER2_RTSCTS=0 (disable flow control on TELEM2)",
      "Set GPS1_TYPE=9 (DroneCAN) for Here 3+ on CAN bus",
      "Set CAN_P2_DRIVER=1, CAN_D2_PROTOCOL=1 (enable CAN2 for GPS)",
      "Set ARMING_CHECK to desired level (29182 for all except GPS in bench test)",
      "Set FS_THR_ENABLE=1 (RC failsafe -> RTL)",
      "Set FS_GCS_ENABLE=1 (GCS failsafe -> RTL)",
      "Set FS_BATT_ENABLE=1 (battery failsafe -> RTL)",
      "Configure kill switch on RC: assign channel to flight mode STABILIZE",
    ],
    guides: [
      { label: "CubePilot Docs", url: "https://docs.cubepilot.org/user-guides/autopilot/the-cube-module-overview", description: "Hardware specs, pinouts, carrier board info" },
      { label: "ArduCopter Full Parameter List", url: "https://ardupilot.org/copter/docs/parameters.html", description: "Every parameter explained" },
      { label: "ArduCopter First Setup", url: "https://ardupilot.org/copter/docs/initial-setup.html", description: "Step-by-step first time setup" },
      { label: "Mission Planner Install", url: "https://ardupilot.org/planner/docs/mission-planner-installation.html", description: "Ground station software for calibration and monitoring" },
      { label: "ArduCopter Flight Modes", url: "https://ardupilot.org/copter/docs/flight-modes.html", description: "GUIDED, AUTO, LOITER, RTL, LAND mode details" },
      { label: "Failsafe Configuration", url: "https://ardupilot.org/copter/docs/failsafe-landing-page.html", description: "RC, battery, GCS failsafe setup" },
    ],
    specs: [
      { label: "Firmware", value: "ArduCopter V4.6.3" },
      { label: "Processor", value: "STM32H757" },
      { label: "IMU", value: "Triple redundant (ICM-42688, ICM-20948, ICM-20649)" },
      { label: "Baud rate", value: "921600 (TELEM2 to Pi)" },
    ],
    testCommands: [
      { command: "python tests2/cube_commands.py", expect: "Heartbeat from system 1, mode changes ACK'd" },
      { command: "python test_cube.py", expect: "Heartbeat, GPS_RAW_INT, ATTITUDE, BATTERY messages" },
      { command: "Mission Planner > Setup > Mandatory", expect: "Accel, compass, RC calibration screens load" },
    ],
    notes: [
      "Always do compass calibration outdoors, away from metal/electronics",
      "Vibration dampener between Cube and frame is essential for IMU health",
      "TELEM2 is the companion computer port — TELEM1 is for external radio telemetry",
    ],
  },
  {
    id: "gps",
    name: "Here 3+",
    category: "navigation",
    role: "GNSS Receiver + Compass",
    description: "Multi-constellation GNSS receiver (GPS + GLONASS + BeiDou + Galileo) with built-in compass. Connected via CAN bus to the Cube. Provides position, velocity, and heading data. The compass is used for yaw estimation.",
    status: "partial",
    connectsTo: ["cube"],
    connectionDetails: "4-pin CAN cable from Here 3+ to Cube CAN2 port. Gets power from Cube through the CAN cable (no separate power needed).",
    setupSteps: [
      "Connect Here 3+ to Cube CAN2 port via 4-pin CAN cable",
      "Set GPS1_TYPE=9 (DroneCAN) in Mission Planner",
      "Set CAN_P2_DRIVER=1 (first CAN driver)",
      "Set CAN_D2_PROTOCOL=1 (DroneCAN protocol)",
      "Reboot Cube after CAN parameter changes",
      "Verify GPS detected: Mission Planner shows satellite count",
      "Mount on GPS mast (highest point on frame, away from electronics)",
      "Outdoor test: wait for 3D fix (fix_type >= 3, at least 8 satellites)",
      "Calibrate compass outdoors: rotate drone in all 3 axes until calibration completes",
    ],
    guides: [
      { label: "Here 3+ User Guide", url: "https://docs.cubepilot.org/user-guides/here-3/here-3+", description: "Wiring, setup, LED meanings, CAN configuration" },
      { label: "ArduCopter GPS Setup", url: "https://ardupilot.org/copter/docs/common-positioning-landing-page.html", description: "GPS parameter reference" },
      { label: "DroneCAN Setup", url: "https://ardupilot.org/copter/docs/common-uavcan-setup-advanced.html", description: "CAN bus configuration for Here 3+" },
      { label: "Compass Calibration", url: "https://ardupilot.org/copter/docs/common-compass-calibration-in-mission-planner.html", description: "Step-by-step compass calibration" },
    ],
    specs: [
      { label: "Constellations", value: "GPS, GLONASS, BeiDou, Galileo" },
      { label: "Accuracy", value: "~2.5m CEP (typical outdoor)" },
      { label: "Interface", value: "CAN bus (DroneCAN protocol)" },
      { label: "Compass", value: "Built-in magnetometer" },
    ],
    testCommands: [
      { command: "python tests2/gps_test.py", expect: "GPS_RAW_INT messages, fix_type >= 3 outdoors, sat count" },
      { command: "python tests2/gps_health.py", expect: "CAN bus check, GPS type, satellite tracking table" },
      { command: "Look at Here 3+ LED", expect: "Flashing blue=no fix, flashing green=GPS lock" },
    ],
    notes: [
      "LED: flashing blue = no GPS lock (normal indoors). Flashing green = GPS lock acquired.",
      "Takes 1-3 minutes for first fix outdoors. Subsequent fixes are faster (almanac cached).",
      "Mount away from power wires and motors — magnetic interference corrupts compass readings.",
      "Indoor testing: fix_type=1 (no fix) is expected. Need clear sky for 3D fix.",
    ],
  },
  {
    id: "pi",
    name: "Raspberry Pi 5",
    category: "companion",
    role: "Companion Computer",
    description: "Runs the Python mission code: camera capture, AI inference (YOLOv8n TFLite), GPS estimation, ground station web server, and sends MAVLink commands to the Cube via mavproxy. Connected to Cube via TELEM2 UART through a mavproxy UDP bridge.",
    status: "verified",
    connectsTo: ["cube", "camera"],
    connectionDetails: "GPIO UART to Cube TELEM2: Pi TX (GPIO14) -> Cube RX, Pi RX (GPIO15) -> Cube TX, Pi GND -> Cube GND. Camera via CSI ribbon cable or USB.",
    setupSteps: [
      "Flash Raspberry Pi OS (64-bit, Bookworm) to SD card",
      "Enable UART: add 'dtoverlay=uart0' to /boot/config.txt",
      "Disable serial console: remove 'console=serial0,115200' from /boot/cmdline.txt",
      "Connect Pi TX/RX/GND to Cube TELEM2 RX/TX/GND (note: TX->RX crossover!)",
      "Install mavproxy: sudo pip install mavproxy (or use system mavproxy at /opt/mavlink/)",
      "Create Python venv: python3 -m venv --system-site-packages pienv",
      "Install deps: pip install -r requirements_pi.txt",
      "Install ai-edge-litert (replaces tflite-runtime on Python 3.13)",
      "Test Cube connection: start mavproxy, run test_cube.py",
      "Test camera: run pi_1_camera.py",
      "Test AI: run pi_2_detect.py --headless",
    ],
    guides: [
      { label: "Pi 5 Getting Started", url: "https://www.raspberrypi.com/documentation/computers/getting-started.html", description: "OS install, first boot, network setup" },
      { label: "Pi UART Configuration", url: "https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-uarts", description: "Enable UART for MAVLink communication" },
      { label: "Our PI_SETUP.md", url: "", description: "Project-specific Pi setup guide (docs/PI_SETUP.md)" },
      { label: "Our CONNECTIVITY.md", url: "", description: "Connection debugging guide (docs/CONNECTIVITY.md)" },
    ],
    specs: [
      { label: "SoC", value: "BCM2712, Quad Cortex-A76 @ 2.4GHz" },
      { label: "RAM", value: "8GB LPDDR4X" },
      { label: "Python", value: "3.13" },
      { label: "UART baud", value: "921600" },
      { label: "IP (local)", value: "192.168.1.121" },
    ],
    testCommands: [
      { command: "python tests/pi_1_camera.py", expect: "Frame: (480, 640, 3) — camera working" },
      { command: "python tests/pi_2_detect.py --headless", expect: "Detections with confidence scores" },
      { command: "python tests/pi_3_benchmark.py", expect: "~250ms avg inference, ~4 FPS" },
      { command: "python test_cube.py", expect: "Heartbeat + GPS + attitude data flowing" },
      { command: "python tests2/pi_diagnostics.py", expect: "All subsystem indicators green" },
    ],
    notes: [
      "Python 3.13 + pyserial = broken serial reads. Use mavproxy as UDP bridge instead.",
      "ai-edge-litert replaces tflite-runtime on Python 3.13 (pip install ai-edge-litert).",
      "Create venv with --system-site-packages to access picamera2 (system package).",
      "Never edit code on Pi — develop on laptop, push to git, pull on Pi.",
    ],
  },
  {
    id: "camera",
    name: "Global Shutter Camera (IMX296)",
    category: "vision",
    role: "Vision Sensor",
    description: "Raspberry Pi global shutter camera with IMX296 sensor. Global shutter means no rolling shutter artifacts during movement — critical for detection from a moving drone. Outputs BGR data despite picamera2 labeling it RGB888.",
    status: "verified",
    connectsTo: ["pi", "lens"],
    connectionDetails: "CSI ribbon cable from camera to Pi CSI port. 6mm CS-mount lens screws onto the camera body.",
    setupSteps: [
      "Connect camera to Pi via 15-pin CSI ribbon cable (blue side toward contacts)",
      "Attach 6mm CS-mount lens (screw on, adjust focus by rotating lens barrel)",
      "Enable camera in raspi-config or ensure it auto-detects",
      "Test: rpicam-hello (should show preview)",
      "Test: python3 pi_1_camera.py (should show 640x480 frames)",
      "IMPORTANT: Do NOT add cv2.cvtColor(frame, cv2.COLOR_RGB2BGR) — data is already BGR",
      "Focus adjustment: twist lens ring until image is sharp at target altitude distance",
    ],
    guides: [
      { label: "picamera2 Documentation", url: "https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf", description: "Python camera library API reference" },
      { label: "Global Shutter Camera", url: "https://www.raspberrypi.com/products/raspberry-pi-global-shutter-camera/", description: "Product page, specs, mounting info" },
      { label: "IMX296 Datasheet", url: "https://www.sony-semicon.com/en/products/is/industry/imx296.html", description: "Sensor specs, pixel size, sensitivity" },
    ],
    specs: [
      { label: "Sensor", value: "Sony IMX296 (1/2.9\", global shutter)" },
      { label: "Resolution", value: "1440x1080 native, using 640x480" },
      { label: "Shutter", value: "Global (no rolling shutter artifacts)" },
      { label: "Output", value: "BGR (despite RGB888 label in picamera2)" },
      { label: "FPS w/ inference", value: "~3.9 FPS" },
    ],
    testCommands: [
      { command: "python tests/pi_1_camera.py", expect: "Live preview, correct colors (no blue tint)" },
      { command: "rpicam-hello", expect: "Camera preview window on Pi monitor" },
      { command: "python tests/pi_8_camera_test.py --headless", expect: "FPS count, motion blur assessment" },
    ],
    notes: [
      "CRITICAL: IMX296 outputs BGR data. Do NOT convert with cvtColor — it double-swaps channels.",
      "Focus ring may need adjustment for different altitudes — sharp at 15m != sharp at 30m.",
      "Global shutter eliminates motion blur from drone movement — key advantage over rolling shutter.",
    ],
  },
  {
    id: "lens",
    name: "6mm CS-Mount Lens",
    category: "vision",
    role: "Optics",
    description: "6mm focal length CS-mount lens for the global shutter camera. Determines the field of view — at 30m altitude, covers roughly 25x19m on the ground.",
    status: "verified",
    connectsTo: ["camera"],
    connectionDetails: "Screws onto the camera body CS-mount thread.",
    setupSteps: [
      "Screw lens onto camera body (CS-mount thread)",
      "Adjust focus: point at object at target detection distance, twist until sharp",
      "Run FOV calibration (pi_6_fov_test.py) to measure actual FOV",
      "Update FOCAL_LENGTH_MM in config.py if measured FOV differs from expected",
    ],
    guides: [],
    specs: [
      { label: "Focal length", value: "6mm" },
      { label: "Mount", value: "CS-mount" },
      { label: "FOV (horizontal)", value: "~48 degrees (calculated)" },
    ],
    notes: [
      "FOV calibration is essential for accurate GPS estimation — wrong focal length = systematic position error.",
      "Run pi_6_fov_test.py on bench: measure physical width visible at known distance, calculate actual focal length.",
    ],
  },
  {
    id: "rc-rx",
    name: "FrSky TW-Mini",
    category: "radio",
    role: "RC Receiver",
    description: "Receives pilot RC commands from the FrSky Twin X14 transmitter. Connected to the Cube RCIN port. Provides manual override and kill switch capability.",
    status: "verified",
    connectsTo: ["cube", "rc-tx"],
    connectionDetails: "3-wire cable (signal, power, ground) from TW-Mini to Cube RCIN port.",
    setupSteps: [
      "Bind receiver to transmitter (follow FrSky pairing procedure)",
      "Connect to Cube RCIN port (signal wire orientation matters)",
      "Calibrate RC in Mission Planner (Setup > Mandatory > Radio Calibration)",
      "Map kill switch: assign a 3-position switch to flight mode channel",
      "Set kill switch positions: Position 1 = STABILIZE (kill), Position 2 = LOITER, Position 3 = AUTO/GUIDED",
      "Test: flip kill switch — should immediately switch to STABILIZE mode",
    ],
    guides: [
      { label: "FrSky TW-Mini Manual", url: "https://www.frsky-rc.com/product/tw-mini/", description: "Receiver specs, binding procedure" },
      { label: "ArduCopter RC Setup", url: "https://ardupilot.org/copter/docs/common-rc-systems.html", description: "RC system configuration in ArduCopter" },
    ],
    specs: [
      { label: "Protocol", value: "ACCESS 2.4GHz" },
      { label: "Channels", value: "Up to 24" },
      { label: "Range", value: "Full range (1km+ line of sight)" },
    ],
  },
  {
    id: "rc-tx",
    name: "FrSky Twin X14",
    category: "radio",
    role: "RC Transmitter (Pilot Controller)",
    description: "The pilot's handheld controller. Always has override priority — flipping the kill switch to STABILIZE instantly gives the pilot full manual control regardless of autonomous mode.",
    status: "verified",
    connectsTo: ["rc-rx"],
    connectionDetails: "Wireless 2.4GHz link to TW-Mini receiver on the drone.",
    setupSteps: [
      "Charge transmitter battery fully before flight",
      "Bind to TW-Mini receiver",
      "Configure stick mode (Mode 2 recommended: left=throttle/yaw, right=pitch/roll)",
      "Map 3-position switch for flight modes (kill switch)",
      "Verify all channels in Mission Planner Radio Calibration screen",
    ],
    guides: [
      { label: "FrSky Twin X14", url: "https://www.frsky-rc.com/product/twin-x14/", description: "Transmitter specs, firmware updates" },
    ],
    specs: [
      { label: "Channels", value: "24" },
      { label: "Protocol", value: "ACCESS / ACCST" },
      { label: "Display", value: "5\" color touchscreen" },
    ],
  },
  {
    id: "model",
    name: "YOLOv8n TFLite",
    category: "software",
    role: "AI Detection Model",
    description: "Custom-trained YOLOv8n model exported to TFLite format for Pi inference. Trained on synthetic composite images (map.jpg + dummy.png overlays). Detects a person/dummy lying on the ground from aerial view.",
    status: "verified",
    connectsTo: ["pi"],
    setupSteps: [
      "Model file: best.tflite (~6MB) in project root",
      "Alternative models in models/ directory for flight day swapping",
      "To swap models: cp models/alternative.tflite best.tflite",
      "Benchmark on Pi: python pi_3_benchmark.py (measure inference speed)",
      "Test detection: python pi_2_detect.py --headless",
    ],
    guides: [
      { label: "YOLOv8 Docs", url: "https://docs.ultralytics.com", description: "Model architecture, training, export" },
      { label: "Our CV_GUIDE.md", url: "", description: "Vision system guide, optimization stages (docs/CV_GUIDE.md)" },
      { label: "TFLite Guide", url: "https://www.tensorflow.org/lite/guide", description: "TensorFlow Lite inference on edge devices" },
    ],
    specs: [
      { label: "Architecture", value: "YOLOv8n (nano — smallest, fastest)" },
      { label: "Input size", value: "640x640" },
      { label: "Inference", value: "~256ms on Pi 5 (3.9 FPS)" },
      { label: "Confidence", value: "0.966 on bench test" },
      { label: "Threshold", value: "0.4 (in vision.py)" },
    ],
    testCommands: [
      { command: "python tests/pi_2_detect.py --headless", expect: "Detection boxes + confidence on dummy" },
      { command: "python tests/pi_3_benchmark.py", expect: "50 inference runs, avg time, min/max/std" },
      { command: "python tests/test_tflite_laptop.py", expect: "TFLite loads and detects on laptop" },
      { command: "python tests/pi_9_resolution_test.py", expect: "Resolution vs speed vs detection tradeoff" },
    ],
    notes: [
      "Trained on synthetic data — may underperform on real outdoor images.",
      "COCO person class (yolov8n.pt pre-trained) is a fallback option.",
      "Lower confidence threshold (0.3 or 0.25) if detection rate is too low from altitude.",
    ],
  },
  {
    id: "mavproxy",
    name: "mavproxy",
    category: "software",
    role: "MAVLink Router / Bridge",
    description: "Routes MAVLink messages between the Cube (serial UART) and multiple endpoints: UDP for Pi Python scripts, TCP for Mission Planner. Essential because Python 3.13 + pyserial has broken serial reads — mavproxy handles the serial layer reliably.",
    status: "verified",
    connectsTo: ["cube", "pi"],
    connectionDetails: "Reads from /dev/ttyAMA0 (UART serial to Cube). Outputs: udpout:127.0.0.1:14550 (Pi scripts) + tcpin:0.0.0.0:5762 (Mission Planner over WiFi).",
    setupSteps: [
      "Install: sudo pip install mavproxy (or use /opt/mavlink/mavlink-venv/)",
      "Start command (full):",
      "  sudo mavproxy.py --master=/dev/ttyAMA0 --baudrate=921600 --streamrate=10 --out=udpout:127.0.0.1:14550 --out=tcpin:0.0.0.0:5762",
      "Verify Cube heartbeat appears in mavproxy console",
      "Verify Pi scripts can connect: python test_cube.py",
      "Verify Mission Planner connects via TCP to Pi_IP:5762",
    ],
    guides: [
      { label: "mavproxy Documentation", url: "https://ardupilot.org/mavproxy/", description: "Command reference, usage guide" },
      { label: "MAVLink Protocol", url: "https://mavlink.io/en/", description: "Message types, protocol spec" },
      { label: "Our CONNECTIVITY.md", url: "", description: "Connection debugging guide (docs/CONNECTIVITY.md)" },
    ],
    specs: [
      { label: "Input", value: "/dev/ttyAMA0 @ 921600 baud" },
      { label: "Output 1", value: "udpout:127.0.0.1:14550 (Pi scripts)" },
      { label: "Output 2", value: "tcpin:0.0.0.0:5762 (Mission Planner)" },
      { label: "Stream rate", value: "10 Hz (--streamrate=10)" },
    ],
    testCommands: [
      { command: "sudo mavproxy.py --master=/dev/ttyAMA0 --baudrate=921600", expect: "Heartbeat from CubeOrangePlus in console" },
      { command: "python test_cube.py (in another terminal)", expect: "Receives heartbeat via UDP:14550" },
      { command: "Mission Planner: TCP > Pi_IP:5762", expect: "MP connects, shows instruments" },
    ],
    notes: [
      "Must run with sudo (serial port access).",
      "Python 3.13 + pyserial serial reads are broken — mavproxy is the workaround.",
      "--streamrate=10 is important: boosts ATTITUDE messages from 0.4 Hz to 7.4 Hz.",
      "Mission Planner connects TCP to Pi IP:5762 over WiFi for live monitoring.",
    ],
  },
  {
    id: "payload",
    name: "Tarot Payload Release",
    category: "payload",
    role: "First Aid Kit Delivery",
    description: "Servo-actuated payload release mechanism for delivering a first aid kit to the detected person (R07). Triggered via MAVLink servo command from the Pi after landing near the target.",
    status: "todo",
    connectsTo: ["cube"],
    connectionDetails: "Servo cable from Tarot mechanism to Cube AUX OUT port (servo channel).",
    setupSteps: [
      "Mount Tarot release mechanism underneath the frame",
      "Connect servo to Cube AUX OUT (configure servo channel in parameters)",
      "Set SERVOx_FUNCTION for the release channel",
      "Test servo actuation via Mission Planner Actions tab",
      "Configure MAVLink command in pi_flight.py for autonomous release",
      "Load test: verify mechanism holds and releases first aid kit reliably",
    ],
    guides: [
      { label: "ArduCopter Servo Setup", url: "https://ardupilot.org/copter/docs/common-servo.html", description: "Configuring auxiliary servo outputs" },
      { label: "MAV_CMD_DO_SET_SERVO", url: "https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_SERVO", description: "MAVLink command to actuate servo" },
    ],
    specs: [
      { label: "Type", value: "Servo-actuated release" },
      { label: "Payload capacity", value: "~500g" },
    ],
    notes: [
      "R07 is a 'should' requirement — bonus points, not mandatory.",
      "Test release mechanism on the ground before flight — verify it doesn't jam.",
      "Consider payload weight in battery life calculations.",
    ],
  },
  {
    id: "buzzer",
    name: "Buzzer",
    category: "flight-controller",
    role: "Audio Feedback",
    description: "Connected to the Cube buzzer port. Plays tones for detection alerts, arming sounds, failsafe warnings. Controlled via MAVLink PLAY_TUNE command.",
    status: "verified",
    connectsTo: ["cube"],
    connectionDetails: "2-pin connector to Cube BUZZER port.",
    setupSteps: [
      "Connect buzzer to Cube BUZZER port (polarity matters)",
      "Set NTF_BUZZ_ENABLE=1 (enable buzzer notifications)",
      "Test: arm drone — should play arming tone",
      "Test MAVLink tune: run pi_3b_buzzer.py",
    ],
    guides: [
      { label: "ArduCopter Buzzer", url: "https://ardupilot.org/copter/docs/common-buzzer.html", description: "Buzzer setup and tone meanings" },
    ],
    specs: [
      { label: "Interface", value: "Cube BUZZER port" },
      { label: "Control", value: "MAVLink PLAY_TUNE or ArduCopter auto-tones" },
    ],
  },
  {
    id: "battery",
    name: "LiPo Battery",
    category: "airframe",
    role: "Power Source",
    description: "Lithium Polymer battery powers all drone systems. Connected via power module to Cube POWER1 port for voltage and current monitoring.",
    status: "verified",
    connectsTo: ["cube", "frame"],
    connectionDetails: "XT60 connector to power distribution board. Power module between battery and PDB provides voltage/current sensing to Cube POWER1.",
    setupSteps: [
      "Connect battery to power distribution board via XT60",
      "Connect power module between battery and PDB, sense cable to Cube POWER1",
      "Set BATT_MONITOR=4 (analog voltage and current)",
      "Calibrate voltage: measure with multimeter, adjust BATT_VOLT_MULT",
      "Set battery failsafe: FS_BATT_ENABLE=1, FS_BATT_VOLTAGE=14.0 (for 4S)",
      "Always balance-charge before flight, check individual cell voltages",
    ],
    guides: [
      { label: "ArduCopter Battery Monitor", url: "https://ardupilot.org/copter/docs/common-power-module-configuration-in-mission-planner.html", description: "Power module calibration, failsafe setup" },
    ],
    specs: [
      { label: "Type", value: "4S LiPo (14.8V nominal)" },
      { label: "Flight time", value: "~15-20 minutes" },
    ],
    notes: [
      "Shows 0.0V when powered by USB only (normal for bench testing).",
      "Never discharge below 14.0V (3.5V per cell) — damages battery permanently.",
      "Always monitor battery in Mission Planner during flight.",
    ],
  },
  {
    id: "motors",
    name: "Motors + ESCs",
    category: "airframe",
    role: "Propulsion",
    description: "Four brushless motors with electronic speed controllers (ESCs). Controlled by the Cube via PWM signals on MAIN OUT 1-4.",
    status: "verified",
    connectsTo: ["cube", "frame"],
    connectionDetails: "ESC signal wires to Cube MAIN OUT 1-4. ESC power from power distribution board.",
    setupSteps: [
      "Connect ESCs to Cube MAIN OUT 1-4 (signal wire orientation matters)",
      "Verify motor order matches ArduCopter QUAD/X layout (front-right=1, back-left=2, etc.)",
      "Test motor direction: Mission Planner Motor Test (props OFF!)",
      "Motors 1,4 should spin CW, motors 2,3 should spin CCW",
      "ESC calibration: follow ArduCopter ESC calibration procedure if needed",
    ],
    guides: [
      { label: "ArduCopter Motor Order", url: "https://ardupilot.org/copter/docs/connect-escs-and-motors.html", description: "Motor numbering, spin direction, testing" },
      { label: "ESC Calibration", url: "https://ardupilot.org/copter/docs/esc-calibration.html", description: "ESC throttle range calibration" },
    ],
    specs: [
      { label: "Count", value: "4 (QUAD/X configuration)" },
      { label: "Spin pattern", value: "1,4 CW / 2,3 CCW" },
    ],
    notes: [
      "ALWAYS remove propellers for motor testing on the bench.",
      "Wrong motor order or wrong spin direction = drone flips on takeoff.",
    ],
  },
];

/** Category display info */
export const HARDWARE_CATEGORIES: { id: HardwareComponent["category"]; label: string; color: string }[] = [
  { id: "airframe", label: "Airframe & Power", color: "#f97316" },
  { id: "flight-controller", label: "Flight Controller", color: "#ef4444" },
  { id: "navigation", label: "Navigation", color: "#22c55e" },
  { id: "companion", label: "Companion Computer", color: "#3b82f6" },
  { id: "vision", label: "Vision System", color: "#8b5cf6" },
  { id: "radio", label: "Radio Control", color: "#06b6d4" },
  { id: "payload", label: "Payload", color: "#f59e0b" },
  { id: "software", label: "Software", color: "#ec4899" },
];

/** Connection diagram — which components connect to which */
export const CONNECTIONS: { from: string; to: string; label: string }[] = [
  { from: "cube", to: "gps", label: "CAN2 (DroneCAN)" },
  { from: "cube", to: "pi", label: "TELEM2 UART (921600)" },
  { from: "cube", to: "rc-rx", label: "RCIN (PWM)" },
  { from: "cube", to: "motors", label: "MAIN OUT 1-4 (PWM)" },
  { from: "cube", to: "payload", label: "AUX OUT (servo)" },
  { from: "cube", to: "buzzer", label: "BUZZER port" },
  { from: "cube", to: "battery", label: "POWER1 (sense)" },
  { from: "pi", to: "camera", label: "CSI ribbon" },
  { from: "camera", to: "lens", label: "CS-mount" },
  { from: "rc-tx", to: "rc-rx", label: "2.4GHz wireless" },
  { from: "pi", to: "mavproxy", label: "UDP 14550" },
  { from: "mavproxy", to: "cube", label: "/dev/ttyAMA0" },
];
